baseurl = "http://www.gility.net/"
title = "Gility"
author = "Alex Mcray"
copyright = "Copyright (c) 20015 - 2016, Alex Mcray; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-uno"

[params]
    name = "Gility"
    description = "This is a test static html website for Gility."
    github = "gility"
